### ISSUE TITLE
录播完之后自动转封装

### ISSUE THREAD

**Issue by H4M5TER** [BililiveRecorder/BililiveRecorder#106]
前两天群里看到的需求，不会写C#，蛮提一个放这，有些想法：
1. 加一个设置选项？
2. 程序目前有使用FFmpeg库吗？或者启用选项再下一个FFmpeg的binary？乃至编译一个只有flv2mp4功能的直接带着？
3. 是否保留源文件？转换出现问题的容错率？

**Comment by Genteure** [comment]
真心不想带 ffmpeg
可能加一个录制结束后调用一个命令的功能。
如果要做这个功能的话，肯定要保留原文件，坏的概率有点高。

先鸽置，过阵子再研究怎么实现吧。想先把 FLV Parser 相关的部分重构一下，改的适合编写比较奇怪的处理逻辑，然后优化一下现在的处理逻辑。收到什么奇奇怪怪的数据的时候自动切开，分个文件，感觉能避免很多录坏掉的文件。
